language: node_js
node_js:
- '0.10'
before_script:
- mv ./id_rsa ~/.ssh/id_ras
before_deploy:
- export PATH="$PATH:$HOME/.local/bin"
after_success:
- pip install --user deis
- dpl --provider=deis --controller=deis.dockware.io --username=philipz --password=$deis_passwd --app=node
notifications:
  email: false
before_install:
- openssl aes-256-cbc -K $encrypted_58448cfceffe_key -iv $encrypted_58448cfceffe_iv
  -in id_rsa.enc -out id_rsa -d
env:
  deis_passwd:
    secure: Gv28Et69D2zZoTF7daj7te2vXzHJ5SZ2pLSTytMFUL1MVYPmjkBAKBmG2aelGSkHdV6GpByGcmkLmpiBEME72ZeHR76qvjWpPkHYvVkLat23NVMYq8Wwq70okN39CQ4lr2n9Ws4kMCnyATs0gqfOoxVDuV5Nha9lNjI2fwLDSeA=
