language: node_js
node_js:
- '0.10'
deploy:
  provider: deis
  controller: http://deis.dockware.io
  app: nodejs
  username: philipz
  password:
    secure: "qQMS8KWKTMm5yrkJYpdZB6fAmzW3Ra1fOF5z6Tf0JnW46puIOuQYdr+1WOHIwN0aN69nJjeQpBFw1QWSctKPB+J376fwJ0GbPMyepWa8GErG9dt2yxF/LihMGDPxTKgGzE/txjIl4LC0eTyA6ARa66wjwCtpnxmdbZ2DTfh4Fjw="
  on:
    repo: philipz/example-nodejs-express
