language: node_js
node_js:
- '0.10'
before_script:
- mkdir ~/.deis && mv ./client.json ~/.deis/client.json
before_deploy:
- export PATH="$PATH:$HOME/.local/bin"
deploy:
  provider: deis
  controller: http://deis.dockware.io
  app: nodejs
  username: philipz
  password:
    secure: l0/uvoaKB/u2oXudxZcv9HFbLQdeDRoHrt6PEyRWrTucior5bF8tugT1FOE2sYrMQRbBJJM0O5GiRIlZ4T6NRns5HuN8MgP/EtELmDe/iuq4GxCyqxuQxJ5wbh+a/ZPirMXJ46RPE+EOsoBC9tPf1avg3DMTiQ1sh3ctLh+O6tg=
  on:
    repo: philipz/example-nodejs-express
notifications:
  email: false
