language: node_js
node_js:
- '0.10'
before_deploy:
- 'deis --version'
deploy:
  provider: deis
  controller: http://deis.dockware.io
  app: klutzy-nailhead
  username: philipz
  password:
    secure: l0/uvoaKB/u2oXudxZcv9HFbLQdeDRoHrt6PEyRWrTucior5bF8tugT1FOE2sYrMQRbBJJM0O5GiRIlZ4T6NRns5HuN8MgP/EtELmDe/iuq4GxCyqxuQxJ5wbh+a/ZPirMXJ46RPE+EOsoBC9tPf1avg3DMTiQ1sh3ctLh+O6tg=
  on:
    repo: philipz/example-nodejs-express
notifications:
  email: false
before_install:
- openssl aes-256-cbc -K $encrypted_58448cfceffe_key -iv $encrypted_58448cfceffe_iv
  -in deis.enc -out deis -d
